apiVersion: simpleapp.github.com/v1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: application-sample
    app.kubernetes.io/part-of: app-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: app-operator
  name: application-sample
spec:
  name: grpc-app
  services:
  - name: backend-sats
    port: 9000
    type: "backend"
    numberofendpoints: 2
    image: ghcr.io/sachintiptur/backend
    version: "satsv5"


